trigger: none
pool: umesh-the-agent

jobs:
  - job: terraform
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        backendServiceArm: 'bittubhaiya_service_connection'
        backendAzureRmOverrideSubscriptionID: '792b5051-461b-4568-abbd-b3d549f22f8c'
        backendAzureRmResourceGroupName: 'rg_servicetest'
        backendAzureRmStorageAccountName: 'testrg0002storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'bittubhaiya_service_connection'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'bittubhaiya_service_connection'