trigger: none
pool: umesh-the-agent

jobs:
  - job: terraform
    steps:
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        backendServiceArm: 'service_connection_norway_client2'
        backendAzureRmOverrideSubscriptionID: '310dec27-9d1f-4f6d-8cc0-356278cce859'
        backendAzureRmResourceGroupName: 'rg_servicetest'
        backendAzureRmStorageAccountName: 'testrg0003storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'


    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'service_connection_norway_client2'
        environmentAzureRmOverrideSubscriptionID: '310dec27-9d1f-4f6d-8cc0-356278cce859'

    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        environmentServiceNameAzureRM: 'service_connection_norway_client2'
        environmentAzureRmOverrideSubscriptionID: '310dec27-9d1f-4f6d-8cc0-356278cce859'